name: Benchmark
channels:
  - conda-forge
  - defaults
  - rapidsai
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - aws-c-auth=0.7.22=h96bc93b_2
  - aws-c-cal=0.6.14=h88a6e22_1
  - aws-c-common=0.9.19=h4ab18f5_0
  - aws-c-compression=0.2.18=h83b837d_6
  - aws-c-event-stream=0.4.2=ha47c788_12
  - aws-c-http=0.8.1=h29d6fba_17
  - aws-c-io=0.14.8=h21d4f22_5
  - aws-c-mqtt=0.10.4=h759edc4_4
  - aws-c-s3=0.5.9=h594631b_3
  - aws-c-sdkutils=0.1.16=h83b837d_2
  - aws-checksums=0.1.18=h83b837d_6
  - aws-crt-cpp=0.26.9=he3a8b3b_0
  - aws-sdk-cpp=1.11.329=hba8bd5f_3
  - binutils_impl_linux-64=2.40=ha1999f0_7
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=2.138=openblas
  - blas-devel=3.9.0=38_h1ea3ea9_openblas
  - bokeh=3.4.2=pyhd8ed1ab_0
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli-python=1.1.0=py39hf88036b_3
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=6.1.0=pyhd8ed1ab_0
  - cairo=1.18.0=hbb29018_2
  - click=8.1.8=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.0=py39h74842e3_2
  - cubinlinker=0.3.0=py39hac6bf05_1
  - cuda-bindings=11.8.7=py39ha1d739b_0
  - cuda-profiler-api=11.8.86=0
  - cuda-python=11.8.7=pyha6e82b0_1
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudf=24.08.03=cuda11_py39_240917_ge479454931_0
  - cuml=24.08.00=cuda11_py39_240808_gb17f2dbbe_0
  - cupy=13.6.0=py39h6e70402_0
  - cupy-core=13.6.0=py39h4601a17_0
  - curl=8.17.0=h4e3cde8_0
  - cytoolz=1.0.1=py39h8cd3c5a_0
  - dask=2024.7.1=pyhd8ed1ab_0
  - dask-core=2024.7.1=pyhd8ed1ab_0
  - dask-cuda=24.08.02=py39_240807_gdda3243_0
  - dask-cudf=24.08.03=cuda11_py39_240917_ge479454931_0
  - dask-expr=1.1.9=pyhd8ed1ab_0
  - debugpy=1.8.16=py39haef64b4_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distributed=2024.7.1=pyhd8ed1ab_0
  - distributed-ucxx=0.39.01=py3.9_240807_g19a66b4_0
  - dlpack=0.8=h59595ed_3
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - fastrlock=0.8.3=py39hd56a1bd_1
  - fmt=10.2.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py39hee96239_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gflags=2.2.2=h5888daf_1005
  - gfortran_impl_linux-64=11.2.0=h7a446d4_16
  - gfortran_linux-64=11.2.0=hc2dff05_2
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - glog=0.7.1=hbabe93e_0
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=9.0.0=hfac3d4d_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=py39h06a4308_0
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kernel-headers_linux-64=4.18.0=he073ed8_8
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_he02047a_1
  - libarrow=16.1.0=hcb6531f_6_cpu
  - libarrow-acero=16.1.0=hac33072_6_cpu
  - libarrow-dataset=16.1.0=hac33072_6_cpu
  - libarrow-substrait=16.1.0=h7e0c224_6_cpu
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=38_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcudf=24.08.03=cuda11_240917_ge479454931_0
  - libcufft=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcuml=24.08.00=cuda11_240808_gb17f2dbbe_0
  - libcumlprims=24.08.00=cuda11_240808_g172c6cb_0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcurl=8.17.0=h4e3cde8_0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.2.0=h69a702a_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.84.2=h37c7471_0
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.24.0=h2736e30_0
  - libgoogle-cloud-storage=2.24.0=h3d9a0c8_0
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libkvikio=24.08.02=cuda11_240807_g6b80a5c_0
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblapacke=3.9.0=38_h6ae95b6_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libparquet=16.1.0=h6a7eafb_6_cpu
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=4.25.3=h08a7969_0
  - libraft=24.08.01=cuda11_240807_g185da16b_0
  - libraft-headers=24.08.01=cuda11_240807_g185da16b_0
  - libraft-headers-only=24.08.01=cuda11_240807_g185da16b_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - librmm=24.08.02=cuda11_240807_g5aa8ebe6_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.0=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=257.10=h085a93f_1
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.7.1=h9d88235_1
  - libucxx=0.39.01=cuda11_240807_g19a66b4_0
  - libudev1=257.10=h085a93f_1
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=h4c95cb1_3
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.43.0=py39h6a678d5_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py39hd7df8f7_1
  - lz4-c=1.9.4=hcb278e6_0
  - make=4.4.1=hb9d3cd8_2
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - matplotlib-base=3.9.2=py39hbfdbfaf_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py39h74842e3_0
  - nccl=2.27.3.1=h03a54cd_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numba=0.60.0=py39h0320e7d_0
  - numexpr=2.10.1=py39hd28fd6d_0
  - numpy=1.26.4=py39h474f0d3_0
  - nvcomp=3.0.6=h56904bc_0
  - nvtx=0.2.13=py39hd399759_0
  - olefile=0.47=pyhd8ed1ab_1
  - openblas=0.3.30=pthreads_h6ec200e_3
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.0.1=h17fec99_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py39h505adc9_0
  - pango=1.54.0=h4c5309f_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.42=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py39h15c0740_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptxcompiler=0.8.1=py39h6461835_4
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=16.1.0=py39h8003fee_1
  - pyarrow-core=16.1.0=py39h176f5a7_1_cpu
  - pyarrow-hotfix=0.7=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pylibraft=24.08.01=cuda11_py39_240807_g185da16b_0
  - pynvml=11.4.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=hc30ae73_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.0.2=py39haa5fa38_0
  - r-base=4.3.2=hb8ee39d_2
  - raft-dask=24.08.01=cuda11_py39_240807_g185da16b_0
  - rapids-dask-dependency=24.08.00=py_0
  - rdma-core=60.0=hecca717_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.3=hc2a1206_0
  - rmm=24.08.02=cuda11_py39_240807_g5aa8ebe6_0
  - s2n=1.4.15=he19d79f_0
  - scipy=1.13.1=py39haf93ffa_0
  - seaborn=0.13.2=py39h06a4308_3
  - sed=4.9=h6688a6e_0
  - setuptools=80.9.0=py39h06a4308_0
  - simplegeneric=0.8.1=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - spdlog=1.12.0=hd2e6256_2
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sysroot_linux-64=2.28=h4ee821c_8
  - tblib=3.1.0=pyhd8ed1ab_0
  - tk=8.6.15=h54e0aa7_0
  - tktable=2.10=h8d826fa_7
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.2=py39hd399759_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - treelite=4.3.0=py39hcb22a9e_0
  - tzdata=2025b=h04d1e81_0
  - tzlocal=5.3=py39hf3d152e_0
  - ucx=1.15.0=ha691c75_8
  - ucx-py=0.39.02=py39_240807_g314778e_0
  - ucxx=0.39.01=cuda11_py3.9_240807_g19a66b4_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xyzservices=2025.10.0=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - aislib==0.1.14a0
      - alembic==1.16.5
      - annotated-types==0.7.0
      - anyio==4.12.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - autogen-agentchat==0.2.40
      - autopage==0.5.2
      - backports-tarfile==1.2.0
      - boto3==1.40.69
      - botocore==1.40.69
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cliff==4.9.1
      - cmaes==0.12.0
      - cmd2==2.7.0
      - colorlog==6.10.1
      - coverage==7.10.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.2.1
      - deprecated==1.3.1
      - diskcache==5.6.3
      - distro==1.9.0
      - docker==7.1.0
      - docutils==0.22.4
      - einops==0.8.1
      - executing==2.2.1
      - filelock==3.19.1
      - flaml==2.3.6
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - id==1.5.0
      - idna==3.11
      - iniconfig==2.1.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.2
      - jaraco-functools==4.4.0
      - jeepney==0.9.0
      - jiter==0.12.0
      - jmespath==1.0.1
      - joblib==1.5.2
      - keras==3.10.0
      - keyring==25.7.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - lightgbm==4.6.0
      - lightning==2.5.6
      - lightning-utilities==0.15.2
      - mako==1.3.10
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - ml-dtypes==0.5.3
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - namex==0.1.0
      - networkx==3.2.1
      - nh3==0.3.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.8.1
      - opt-einsum==3.4.0
      - optree==0.17.0
      - optuna==2.10.0
      - pandas-plink==2.2.9
      - parso==0.8.5
      - patsy==1.0.2
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - prettytable==3.16.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.3
      - py==1.11.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyecharts==2.0.9
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytest==8.4.2
      - pytest-cov==7.0.0
      - python-dotenv==1.2.1
      - pytorch-lightning==2.5.6
      - pyyaml==6.0.3
      - readme-renderer==44.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.9.4
      - rich-argparse==1.7.2
      - rpy2==3.5.16
      - s3transfer==0.14.0
      - safetensors==0.7.0
      - scikit-learn==1.6.1
      - secretstorage==3.3.3
      - simplejson==3.20.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - statsmodels==0.14.5
      - stevedore==5.5.0
      - swanlab==0.7.5
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.8.0
      - torchmetrics==1.8.2
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.4.0
      - twine==6.2.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - umap-learn==0.5.9.post2
      - urllib3==1.26.20
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - xarray==2024.7.0
      - xgboost==2.1.4
      - xlsxwriter==3.2.9
      - yarl==1.22.0